version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:stretch
      steps:
      - checkout
      - run:
          name: RaDiX - Build ISO
          command: bash code/build/build-iso.sh
